### ISSUE TITLE
Standard(s) should be mandatory for NC

### ISSUE THREAD

**Issue by Praxie** [sives/Plio#100]
Standard(s)* - links to one or more existing Standards.  Is pre-filled if you have added the Non-conformity when there is a Standard already selected.

**Comment by Praxie** [comment]
https://trello.com/c/YFuojrCe/233-i100-standard-s-should-be-mandatory-for-nc-there-may-be-multiple-standards-linked-to-nc-not-only-one

**Comment by Praxie** [comment]
4 hours

**Comment by sives** [comment]
We decided that it shouldn't be mandatory
