### ISSUE TITLE
Risk scoring - default values

### ISSUE THREAD

**Issue by sives** [sives/Plio#103]
When filling in a new Risk Score, the username field should default to the current user, and the date field should default to the current date.  Also, when clicking on the date picker, there should be a visual indicator of todays date on the date grid (these are general rules that apply to all similar fields on Plio cards and sub cards)

**Comment by Praxie** [comment]
Done

**Comment by sives** [comment]
The username field does now default to the current user.  However the date field in the Risk card (and in other cards) defaults to yesterdays date.   Also, there is no visual indicator of todays date on the date grid.

**Comment by Praxie** [comment]
> However the date field in the Risk card (and in other cards) defaults to yesterdays date

I can't reproduce this.

**Comment by Praxie** [comment]
@sives it seems to be resolved in the current release.

**Comment by sives** [comment]
Label on the vertical axis of the risk scoring matrix should be "Impact" and not "Impacts"
