### ISSUE TITLE
"Complete" button in Work inbox screen is confusing

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#109]
Change the colour of the button to blue (like the edit button) and also remove the tick symbol from the button.

User feedback - the current graphical representation of the button makes it look as if the action has already been completed.  The strong green colour gets a bit confused with our traffic light green, which signifies that everything is ok and done with this item. 

The same applies to the "Complete" button in the NC card (and any other buttons in cards or subcards - these must not be green)

**Comment by Praxie** [comment]
**v0.2.36** feature
