### ISSUE TITLE
Need better default list of Risk types

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#110]
We need a better default list in the Org settings:
Credit risk
Liquidity risk
Market risk
Operational risk
Regulatory risk
Reputational risk
Infosecurity risk

Also, the button in the Risk types subcard in Org settings should be labelled "Add risk type" and not "Add risks type".

**Comment by Praxie** [comment]
@sives could you provide abbreviations as well please?
![screen shot 2016-10-06 at 12 57 12 pm](https://cloud.githubusercontent.com/assets/2095940/19148249/6cc64694-8bc4-11e6-9ee8-2f0084dd006b.png)

**Comment by sives** [comment]
In the Screen spec v1.2, Risk types is specified as a SC25 Simple selection list, not as a 2 column selection list.  There is no requirement in the spec for abbreviations.
