### ISSUE TITLE
Change list of default Standards types

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#112]
List should be amended to:
Process    (PRO)
Policy       (POL)
Checklist  (CHK)
Compliance management objective  (CMO)
Compliance obligation   (COB)
Standard operating procedure   (SOP)
Work instruction  (WORK)
Product specification    (SPEC)
Risk control   (RSC)
Section header  (no abbreviation)

**Comment by Praxie** [comment]
Fixed
