### ISSUE TITLE
Compliance standards screen - list view item design

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#113]
When the Standard type is "Section header" or "Other", do not display the Standard type on the 2nd line LHS of the List view item panel, but just leave this 2nd line blank.  This rule applies to all three List views in this screen.

**Comment by Praxie** [comment]
It will leave a white space at the bottom of the list item. I think that it's better to keep it this way. This grey text isn't so catchy.

**Comment by sives** [comment]
I'll just remove the option of "Other" from the default list of Standard types, that deals with most of the problem.
