### ISSUE TITLE
Icon in desktop notifications panel

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#117]
The icon that appears at the top left hand side of the desktop notifications panel is not correct.  Currently it is represented as a black circle with a Plio logo in the middle.   It should be simply the blue Plio "P" logo character, just like we are using as the web favicon e.g. as displayed in the browser tab.
![screen shot 2016-09-21 at 12 24 32](https://cloud.githubusercontent.com/assets/2675608/18709127/643c804e-7ff6-11e6-8d57-b1d24a12b83e.png)

**Comment by unplugged** [comment]
In other words, it should be rendered like this:
![screen shot 2016-09-21 at 12 25 50](https://cloud.githubusercontent.com/assets/2675608/18709160/95ef2f7e-7ff6-11e6-9a75-bffa059dae41.png)

**Comment by Praxie** [comment]
@sives it's just a small easter egg :)
Magic 8-Ball reference. The secondary text in the notification is random.
https://en.wikipedia.org/wiki/Magic_8-Ball
