### ISSUE TITLE
User invitation message for already-registered users

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#118]
The current message ("User was added to this organization immediately") is confusing. It should be changed to:

"[user] is already a Plio user.  This user has now been added to the [org name] organization in Plio"

**Comment by Praxie** [comment]
Fixed

**Comment by sives** [comment]
![screen shot 2016-10-05 at 16 00 48](https://cloud.githubusercontent.com/assets/2330529/19118676/0eff9ab0-8b15-11e6-8817-f81d2afa9cf0.png)

**Comment by sives** [comment]
Please make this text a 100% black colour instead of grey (for clarity)

**Comment by Praxie** [comment]
**v0.2.36** feature

**Comment by sives** [comment]
Looks good.
