### ISSUE TITLE
Display of 2nd file attachment in Compliance standards card

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#120]
When adding a 2nd file attachment, we should display the rectangular icon corresponding to this 2nd attachment below the main document window, to the right hand side of the rectangular icon for the first file attachment.

![screen shot 2016-09-21 at 12 40 30](https://cloud.githubusercontent.com/assets/2675608/18709559/a0a55edc-7ff8-11e6-86bd-9eb941afac5e.png)

**Comment by Praxie** [comment]
@sives I'm not sure if this is a good idea because the word document + the rectangular icon represent a single source file and you want to want to mix both source files within a single section.

**Comment by sives** [comment]
You are right.  Let's just leave it the way it is.
