### ISSUE TITLE
Change traffic light colour state list for CAs and PAs

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#122]
Users are getting confused that green means completed, so I think the list of states and colours should be changed to:

List of possible CA/PA statuses in a 6-step workflow (9):
In progress -  (yellow)
In progress - due for completion today (amber)
In progress - completion overdue (red)
In progress - completed, not yet verified (yellow)
In progress - completed, verification due today (amber)
In progress - completed, verification overdue (red)
Completed - failed verification (red) (user needs to create a new PA or CA)
Completed - verified as effective (green)
Deleted - (no colour)

List of possible CA/PA statuses in a 3-step workflow (5):
In progress -  (yellow)
In progress - due for completion today (amber)
In progress - completion overdue (red)
Completed - (green)
Deleted - (no colour)

I've updated this in the latest version of the Screen spec v1.2.

**Comment by Praxie** [comment]
@sives Bootstrap has no yellow labels predefined. It won't look good with white text.
![screen shot 2016-10-11 at 3 14 13 pm](https://cloud.githubusercontent.com/assets/2095940/19269874/846e1056-8fc5-11e6-9ada-719d50417a5e.png)

**Comment by Praxie** [comment]
It looks better with darker yellow
![screen shot 2016-10-11 at 3 20 20 pm](https://cloud.githubusercontent.com/assets/2095940/19269985/4376595e-8fc6-11e6-8703-451ce3649768.png)

**Comment by sives** [comment]
Yes, agreed, darker yellow is better

**Comment by Praxie** [comment]
**v0.2.36** feature

**Comment by sives** [comment]
Looks good.
