### ISSUE TITLE
Risk controls object is badly designed.

### ISSUE THREAD

**Issue by unplugged** [sives/Plio#123]
This is a mistake in my design and in my specification, not a mistake in the software.   

User feedback is that the Risk control object does not correspond to how customers think a Risk control should work in the system.  They think it should be a type of Standards document (which is why I've added this to the Standards type list).  

So we need to remove the Risk control subcard from the Risk card, and replace it with a Preventative actions subcard (so it will look similar to the Non-conformities card in this respect i.e. user can add either Corrective actions or Preventative actions to the card).   

Sorry about this error.  In a future version of the system, users should be able to add one or more Risk controls (which are a specific type of Standards document) as a subcard to a Risk card.   For now, we will just implement the quick solution described above.

**Comment by Praxie** [comment]
**v0.2.36** feature

**Comment by sives** [comment]
Looks good.
