### ISSUE TITLE
Wrong list of users

### ISSUE THREAD

**Issue by sives** [sives/Plio#125]
When I'm in the Plio organisation and I add a Non-conformity and then try and change the "Identified by" user to someone else, I get shown a list of all the users in the system.  I should be shown just the list of users in the Plio organisation.   

This issue also applies to selecting users for assigning Corrective actions.  I suspect that it is a problem in all the user selection fields.

**Comment by Praxie** [comment]
Fixed

**Comment by sives** [comment]
When in the Plio Ltd organisation, James tested clicked on the "Identified by" field in the NC10 non-conformity card to switch this to a different user, he was presented with a list with no users i.e. a blank list. 
 
When, in the same screen, I click on this field I am presented with a list of all 7 users in the system.

 We should both have seen the same list of 3 users in the Plio organisation i.e. Mike, Steve and James.

**Comment by Praxie** [comment]
Fixed
