### ISSUE TITLE
Increase max length of title fields

### ISSUE THREAD

**Issue by sives** [sives/Plio#126]
Increase max length of title fields (e.g. Non-conformity title name) from 40 to 80 characters

**Comment by sives** [comment]
Error message is now incorrect - it says you cannot exceed 40 characters, but should be 80 characters.

![screen shot 2016-10-05 at 16 19 58](https://cloud.githubusercontent.com/assets/2330529/19119412/8fa5f2d4-8b17-11e6-8f50-2266b0b103d2.png)

**Comment by sives** [comment]
To ensure that the abbreviation is not longer than 40 letters, we should stop the user entering the 41st character in the field, not allow it and then display an error message at the top.  

Then it's much more obvious to the user what they are doing wrong with their data entry.

This should be a consistent field validation behaviour across the system whenever any text is entered which is too long.

**Comment by sives** [comment]
This seems to be working now

**Comment by Praxie** [comment]
@sives no, the input is not limited to 80 characters yet. It's possible to enter a string of any length.

**Comment by Praxie** [comment]
**v0.2.38** feature

**Comment by sives** [comment]
Tested and verified.
