### ISSUE TITLE
Colour of non-conformity traffic lights

### ISSUE THREAD

**Issue by sives** [sives/Plio#127]
A non-conformity categorised as minor with a 3 step workflow (NC7 in Plio Ltd) that has just been created, has no corrective actions associated with it yet, and is awaiting action should be coloured amber and not green (see Screen spec v1.2) .

A non-conformity categorised as critical with a 6 step workflow (NC8 in Plio Ltd)  that has just been created, has no corrective actions associated with it yet, and is awaiting analysis should be coloured amber and not red (see Screen spec v1.2) .

**Comment by Praxie** [comment]
@sives I can't confirm this issue. I see correct label colors.

**Comment by sives** [comment]
I just tested it again in v0.2.35 and it is working fine, so I will close the issue.
