### ISSUE TITLE
Remove "lorem ipsum dolor est"

### ISSUE THREAD

**Issue by sives** [sives/Plio#130]
Remove this text string from the "Add" modal in the Work inbox screen (just leave this second line blank in each selection panel)

Also, remove the Add Risk control option from this modal.

**Comment by Praxie** [comment]
@sives Why do we need to remove a "Risk control" option from the Add modal in the Work inbox screen?

**Comment by Praxie** [comment]
I've jus found the answer here: https://github.com/sives/Plio/issues/123

**Comment by Praxie** [comment]
![screen shot 2016-10-03 at 5 32 38 pm](https://cloud.githubusercontent.com/assets/2095940/19041111/749d860c-898f-11e6-9bc3-f53e30156584.png)

**Comment by Praxie** [comment]
![screen shot 2016-10-03 at 5 30 23 pm](https://cloud.githubusercontent.com/assets/2095940/19041118/7a7fbe0a-898f-11e6-86f5-dbb44b779416.png)

**Comment by Praxie** [comment]
@sives which one do you prefer?

**Comment by sives** [comment]
I prefer the first one - the one with a larger target zone for your finger or mouse pointer

**Comment by Praxie** [comment]
Fixed
