### ISSUE TITLE
Change List view item fields in Work inbox

### ISSUE THREAD

**Issue by sives** [sives/Plio#131]
The title of the Non-conformity or Corrective action/preventative action should be on the first line of the List view item panel, and not on the 2nd line (I know we've discussed this before at length, but I think we must have got our wires crossed).    The action required text string should be on the 2nd line, after the unique ID.

There is a good reason for doing it this way.  When you look at some actual data in Plio, the action required text is almost always the same from one work item to the next, so the list view conveys almost no information if you put the action required text at the top.  What's the point of looking at a list view where every item looks the same at first glance?

**Comment by Praxie** [comment]
**v0.2.36** feature
