### ISSUE TITLE
Daily recap issues

### ISSUE THREAD

**Issue by sives** [sives/Plio#140]
The right hand column "Date & time" values are all being shown as the same i.e. 12.00 AM.   They should correspond to the item change time, and should not all be the same.

Also, the column title label "Date & time" needs to be changed to "Time".

**Comment by Praxie** [comment]
@sives 
> The right hand column "Date & time" values are all being shown as the same i.e. 12.00 AM. They should correspond to the item change time, and should not all be the same.

That means that these actions were completed at the same time. Here is the screenshot of the latest Daily recap:

![screen shot 2016-09-28 at 5 44 00 pm](https://cloud.githubusercontent.com/assets/2095940/18918410/6573c334-85a3-11e6-997e-de42be5ae76a.png)

**Comment by sives** [comment]
OK, I had thought it was a bug in the time display code but it isn't.   We just need to change "Date & time" to "Time".   Also we need to give users a User preferences option to "Receive daily recap emails" (or not, mark with a checkbox).  This option should be shown in a separate User preferences section titled:   Preferences for [org name]

**Comment by Praxie** [comment]
@sives  I removed the bug label because it's a 2 minutes job to change the title label "Date & time".
"Receive daily recap emails" option will take more time.

**Comment by sives** [comment]
OK, makes sense

**Comment by Praxie** [comment]
*v0.2.36*

**Comment by sives** [comment]
The checkboxes in the Daily recap email subcard are not showing the daily recap settings that are already set (all checkboxes are empty, yet I am receiving daily recap emails for these organizations).

By the way, the default behaviour should be that Daily recap emails are enabled for all users, until a user decides to go to My preferences and disable it.

**Comment by Praxie** [comment]
@sives it's probably a bug caused by outdated data. I'll take a look at this.

**Comment by Praxie** [comment]
@sives I'll run a DB query to fix this bug for existent users.
