### ISSUE TITLE
Capitalizing names when registering account

### ISSUE THREAD

**Issue by jives95** [sives/Plio#142]
When signing up if i put 'james ives' my username becomes 'james ives', but for standardising names the first letters should be capitalized so entering 'james ives' automated to 'James Ives'

**Comment by sives** [comment]
We should automatically correct to uppercase when the user accepts the invitation and Plio creates their account for the first time.  However if they go into the User directory to change the name back to lower case we should allow this.

**Comment by Praxie** [comment]
![38a9b9871b9b6f492e0a0151f38f4e3d](https://cloud.githubusercontent.com/assets/2095940/19079729/42bef412-8a5d-11e6-9974-e4abea045262.gif)

@sives What do you think about this solutions?

**Comment by sives** [comment]
Yes, it's good
