### ISSUE TITLE
Redesign of List view selector

### ISSUE THREAD

**Issue by jives95** [sives/Plio#146]
In the dropdown section for 'Risks by -' you have 'by type, by status etc', change this by removing 'by' and just having 'type, status etc'

**Comment by sives** [comment]
This is a general point which applies to the wording of all the List view selectors in all the main screens (Compliance standards, Non-conformities, Risks, Work inbox).

Top (visible) line should read:   "Risks by - type"
Lower section should read:
- type
- status
-department/sector
-deleted

**Comment by sives** [comment]
I will provide a list of the amended List view titles

**Comment by sives** [comment]
Here is the amended list (note - I have shortened some titles as well)

Compliance standards screen:
Standards - by section
Standards - by type
Standards - deleted

Non-conformities screen:
NCs - by magnitude
NCs - by status
NCs - by department
NCs - deleted

Risk register screen:
Risks - by type
Risks - by status
Risks - by department/sector
Risks - by deleted

Work inbox screen:
Work - my current 
Work - team current
Work - my completed
Work - team completed
Work - my deleted
Work - team deleted

**Comment by RevelsGit** [comment]
https://trello.com/c/h1yf4pQi/328-1-5-i146-redesign-of-list-view-selector

**Comment by Praxie** [comment]
**v0.2.35** feature
