### ISSUE TITLE
Logout/Login back to your previous Home screen

### ISSUE THREAD

**Issue by sives** [sives/Plio#148]
When you log out of the system (or you are logged out by Plio) and you come back to Plio later and log in again, you are logged in to the Home screen of the first organization in the org list.  

You should be always be taken back to the Home screen of the same organization you were in when you logged out (or were logged out).

**Comment by RevelsGit** [comment]
https://trello.com/c/j8ApqUcA/319-1-i148-logout-login-back-to-your-previous-home-screen

**Comment by Praxie** [comment]
**v0.2.36** feature
