### ISSUE TITLE
Traffic lights in List view item panels are confusing

### ISSUE THREAD

**Issue by sives** [sives/Plio#149]
The colours of the round traffic light symbols in the LHS List view item panels are confusing to users, because they are different to the colour codes used on the RHS cards.

We should simplify this by removing the round traffic light symbols in the LHS List views in the Non-conformities and Work inbox screens.   

For Non-conformities, we should add a coloured rectangular box behind the unique NC123 identifier in the LHS list view, to match the appearance and colour of the NC123 identifier in the RHS non-conformity card (to the right of the title).

Similarly, for Work inbox items, we should add a coloured rectangular box behind the unique CA123 or NC123 or RK123 identifier in the LHS list view, to match the appearance and colour of the corresponding unique identifier in the RHS card.

Then we just have one type of colour code that is used in the same way on both the LHS and RHS of the screen, which is much less confusing.

**Comment by sives** [comment]
The List view design in the Non-conformities screen now looks good.  

We agreed to leave the List view design of the Work inbox  as it is (except that the primary title must be the action title, and not the To Do title, which should be the secondary title on the 2nd line of the List view item panel)

In the Risk register, we agreed to use the large square traffic light containing the risk score, and to make the risk ID normal text, rather than a coloured rectangle traffic light.  (there should never be more than one traffic light in a list view item panel, otherwise it confuses the user).

**Comment by sives** [comment]
Risk register List views now looking good.  

List view design of the Work inbox still needs changing (primary title must be the action title, and not the To Do title, which should be secondary on the 2nd line)

**Comment by Praxie** [comment]
**v0.2.35** feature

**Comment by sives** [comment]
Can change the secondary text format from "CA4 - Complete action" to "CA4 - Complete this action" for added clarity please?
