### ISSUE TITLE
Making it easier to close a card (especially big ones)

### ISSUE THREAD

**Issue by sives** [sives/Plio#151]
Currently the only way to close a card that has been opened for editing is to click on the Close button. 

If the user clicks anywhere on the screen outside the card boundary, this should also close the card.

**Comment by Praxie** [comment]
There is an issue with this approach. The closing action triggers a validation. So if the user will accidentally click anywhere on the screen outside the card boundary and there will be some invalid/unsaved content, the error message will be displayed.

**Comment by sives** [comment]
I agree that clicking outside the card boundary is not the best solution.   Let's leave this issue to a later release, since it isn't critical.
