### ISSUE TITLE
Saving of new Risk types in Org settings

### ISSUE THREAD

**Issue by sives** [sives/Plio#155]
When a user adds a new Risk type without also providing a short name (in the right hand column) then the new Risk type is not saved.  There is also no warning from the system that it is not going to save the new Risk type.   

Expected behaviour: the new Risk type should be saved even if the user doesn't enter a short name, since the short name is not mandatory.

Also, it is possible to type in short names that are longer than 4 characters.  Maximum length is  supposed to be 4 characters (this issue is related to issue 111, Standards types, which uses the same subcard)

**Comment by Praxie** [comment]
Fixed.

**Comment by sives** [comment]
Need to stop user typing in more than 4 characters into the field (as opposed to letting them type in lots of characters and then generating an error message on card closing)

**Comment by Praxie** [comment]
v0.2.35
