### ISSUE TITLE
Appearance of action buttons in cards is confusing for users

### ISSUE THREAD

**Issue by sives** [sives/Plio#157]
The appearance of action buttons within certain cards e.g. the "Complete" and "Verify" buttons, is a bit confusing to users, because they look like large traffic lights.  

Solution:
Make sure all the coloured buttons in the system (including the blue "Edit" buttons in the card headers) have a colour gradient (just like the green "New issue" and "Comment" buttons in Github, for example), together with a button outline (which should be a darker version of the same colour).  

This makes it a lot easier for the user to distinguish between a button and a traffic light data items (which should not have a gradient, and should not have an outline).  

The colour should change from lighter at the top of the button to darker at the bottom, in an identical way to Github buttons.

**Comment by sives** [comment]
As discussed in the call - remove the icon symbols from the Complete, Verify and Edit buttons (keep the icons on the Add buttons, and on the home screen Invite and Report a non-conformity buttons)

The tick icons are especially confusing, they look like status items rather than buttons.

**Comment by Praxie** [comment]
**v0.2.36** feature

**Comment by sives** [comment]
Needs a bit more gradient on the buttons (i.e. slightly darker at bottom, slightly lighter at top

**Comment by Praxie** [comment]
@sives done

**Comment by Praxie** [comment]
Before:
![screen shot 2016-10-11 at 5 52 25 pm](https://cloud.githubusercontent.com/assets/2095940/19282204/fd7baadc-8ff5-11e6-99b4-3ba8266315ee.png)
After:
![screen shot 2016-10-11 at 5 52 30 pm](https://cloud.githubusercontent.com/assets/2095940/19282207/01a529a8-8ff6-11e6-8f6e-5af55f93f883.png)

**Comment by Praxie** [comment]
@sives I think that you can close this issue now.
