### ISSUE TITLE
Signup process - invitation text

### ISSUE THREAD

**Issue by sives** [sives/Plio#16]
The customisable invitation text does not show up in the invitation email.  It should.

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/139

**Comment by sives** [comment]
Custom text is now showing up in invitation.  However, the styling of the invitation message needs to to be changed so that it looks more like an email from a colleague and less like a marketing promotion email.  Here's how Basecamp format their emails (see below).  We don't need to worry about the user thumbnail image or the video URL link, but otherwise it would be good to follow their style.   Put the Plio logo right at the bottom of the message, about half the size it is now, and justified to the left.

![basecamp invitation](https://cloud.githubusercontent.com/assets/2330529/15601851/b615be3a-23e9-11e6-9545-40df1b6f83ba.png)

**Comment by sives** [comment]
We also need to change the styling of the "You have been added to the XYZ organization" email and the email verification email, to fit in with the new style

**Comment by Praxie** [comment]
![screen shot 2016-06-09 at 3 10 58 pm](https://cloud.githubusercontent.com/assets/2095940/15929367/46132a0c-2e55-11e6-899e-b6a808657ed3.png)
![screen shot 2016-06-09 at 3 14 05 pm](https://cloud.githubusercontent.com/assets/2095940/15929371/485625a8-2e55-11e6-897a-d28b8abd28ff.png)

**Comment by Praxie** [comment]
@sives We need to decide if we need to completely replace the old template, or we'll use the old one for different kinds of email.

**Comment by Praxie** [comment]
![screen shot 2016-06-09 at 3 16 13 pm](https://cloud.githubusercontent.com/assets/2095940/15929423/9b64e3ba-2e55-11e6-90f9-13b5c05f725b.png)

**Comment by Praxie** [comment]
Document update notifications, email verifications, "added to notify list" kind of emails.

**Comment by Praxie** [comment]
Invitation template is updated, for other email types it's better to submit another issue.

**Comment by sives** [comment]
These new email layouts look good
