### ISSUE TITLE
"Add new item" behaviour in selection lists is not obvious to users

### ISSUE THREAD

**Issue by sives** [sives/Plio#160]
When users try to add a new item that isn't in an existing list of items (e.g. adding a new Standards section) they are getting confused.

It's not clear enough to them that they need to click on the "Add 'new' section" dropdown to actually add this new section into the list.   So they click out of this field prematurely, and think that they've added this new section when they haven't.  

Solution:
Jack is going to provide a clearer user interface treatment for this feature.
Also, we need some Javascript code to ensure that if users try to click out of this field into another field without clicking on the Add 'new' section dropdown, then the 'New" text is removed from the field.

**Comment by sives** [comment]
Jack has provided example UI for this (go to Standards screen, go "Edit" then type into Book section list) which is nearly right, but not exactly as I want it.

What I want is to use the same dynamic "Add......" label under the selection list that we currently have working in the system, but to put it into a blue button box (instead of displaying it as just black text on a white background)

**Comment by Praxie** [comment]
Implemented in the current release.
