### ISSUE TITLE
Add new field called "Score type" to SC15 Risk score subcard

### ISSUE THREAD

**Issue by sives** [sives/Plio#164]
Feedback from Ian Scaife at Clifton - we need a way to specify whether the risk score relates to the Inherent risk to the Residual risk.

Inherent risk is the overall risk before treatment of that risk.
Residual risk is the new, reduced level of risk once the risk treatment has been applied.

So we need a new field  called "Score type" with the selection options "Inherent risk" and "Residual risk".   

The ordering of the fields in the subcard is:
- Score type: (user selects "Inherent risk" or "Residual risk")
- Scored by:
- Date:

Layout of fields on the indivdual item subcard headers is as follows: (showing 2 individual items):
            Inherent           27 Sep 2016                75
            Residual           27 Sep 2016                34

On the top level sub card header it is the most recent Residual risk score that is displayed.  If there is no Residual risk score entered yet, then the Inherent risk score is the one that is displayed.  This same rule is applied to the score that is displayed in the LHS List view in the Risk register screen.

**Comment by Jennyyen** [comment]
Oh really. I also have to face this issuse the same you. I need to find a good solution for this one

**Comment by Praxie** [comment]
@sives will it affect the workflow?

**Comment by sives** [comment]
@Praxie no it does not affect the workflow in any way

**Comment by Praxie** [comment]
I think that we need to display the score type in the score header if the Residual risk score is more important thenInherent risk score. 
![screen shot 2016-09-28 at 4 45 01 pm](https://cloud.githubusercontent.com/assets/2095940/18915824/f781e160-859a-11e6-84c1-de6a2eac893c.png)

**Comment by sives** [comment]
Yes, agreed, that is what I thought I indicated above.  The layout should be slightly different to what you have shown (see my original comment above).   First column should be Type, second column should be date, third column should be Low/Med/High, fourth item should be score box.

For example:
>  Residual_____21 Sep 2016______Medium [51]

**Comment by Praxie** [comment]
@sives Sorry I didn't notice that. Got it.

**Comment by Praxie** [comment]
![screen shot 2016-10-05 at 4 56 42 pm](https://cloud.githubusercontent.com/assets/2095940/19116024/bf436274-8b1c-11e6-8172-b825baa16864.png)
@sives Do we need to have another column here?

**Comment by Praxie** [comment]
'Score type'

**Comment by sives** [comment]
(I'm assuming that this question relates to the Read mode of the card - the ordering of the edit mode subcard header has already been specified above)

Yes we do need another column, and the order needs to be as follows:

Score type                 Score               Scored date         Scored by

**Comment by Praxie** [comment]
@sives thanks. Is it OK to put the hyphen between a score type and date?
![6de8bc01311309686c98515cbf90f385](https://cloud.githubusercontent.com/assets/2095940/19122885/2f72faf6-8b35-11e6-86dc-9761cfb7fe6f.png)

**Comment by Praxie** [comment]
This issue can be considered as "resolved" if these changes are aproved.

**Comment by sives** [comment]
Mike - your design with the hyphen is good.  We should just default the type field to "Inherent" and then I can close the issue

 (sorry - I had previously asked for no default value - but on reconsideration it is better to have a default value here - not everyone will immediately understand the difference between "Inherent" and "Residual", and "Inherent" is a safe default value)

**Comment by Praxie** [comment]
v0.2.35
