### ISSUE TITLE
Behaviour on clicking on Invite button in Invite card

### ISSUE THREAD

**Issue by sives** [sives/Plio#166]
When you click on the Invite button in the Invite card, the users sees a "no-entry" symbol (a circle with a diagonal line) immediately after clicking.  This should not be displayed.  If the system needs to pause to process the action, it should display in the normal way (i.e. the new state of the button label together with a spinning  indicator).

I have seen this behaviour with one or two other buttons, it should be changed in all of them that follow this pattern.

**Comment by Praxie** [comment]
@sives this is a standard behaviour of the disabled button that was provided by bootstrap and is commonly used in web design.
It means that it doesn't make sense clicking on the "Loading..." button. That's why there is a "no-entry" symbol instead of a pointer.

**Comment by Praxie** [comment]
I think that it's better to keep it this way. What do you think, @sives?

**Comment by sives** [comment]
I understand the issue and that this is standard practice in web site design but it is not standard practice in app design, and the Plio UI has much more of an app-style design than a web-style design.   We already handle this issue in Plio by immediately changing the button label on the click event, and showing the progress spinner, so there is no need to display a no-entry symbol as well.
