### ISSUE TITLE
Signup process - invitation not found

### ISSUE THREAD

**Issue by sives** [sives/Plio#17]
When you accept an invitation, you first see a screen which says "Invitation not found" for 0.5 to 1 sec (when the invitation is actually valid) before it is quickly overwritten by the correct screen - confusing.  This misleading statement should not display at any time unless the invitation is not actually valid.

**Comment by Praxie** [comment]
Copy that.

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/143

**Comment by sives** [comment]
Fixed.  However, there needs to be a clear instruction to the user about what they need to do in the new User details screen.  Suggest the following wording, on 2 separate lines at the top of the card.

Your Invitation to join the Clifton Asset Management compliance management system on Plio. 
Please enter your name and then a password to protect your account.
