### ISSUE TITLE
Reporting of beta user activity

### ISSUE THREAD

**Issue by sives** [sives/Plio#171]
Provide a daily recap report of beta user activity (1 daily email per organization.
Only send it if there is actual activity that day.  
Send email to 2 specific addresses (steve.ives@pliohub.com and jamesalexanderives@gmail.com)
This daily recap function is not affected by any recap-related changes in User preferences.

**Comment by sives** [comment]
Mike - so that I can verify this is working, could you create a new organization to which I don't have access, give it the name "Shift Bioscience" then add a couple of Standards documents, and I will look out for the Daily Recap email to come through.

**Comment by Praxie** [comment]
@sives done

**Comment by sives** [comment]
Its working fine.
