### ISSUE TITLE
User invitation message for already-invited users

### ISSUE THREAD

**Issue by sives** [sives/Plio#178]
This is not the correct behaviour.  If an invitation has been sent and not previously accepted, and another invitation is made, Plio should just send that invitation out, not give the message "Failure..."

![screen shot 2016-10-05 at 16 00 48](https://cloud.githubusercontent.com/assets/2330529/19118790/6ec18760-8b15-11e6-933a-16f3a6219c99.png)

**Comment by Praxie** [comment]
4h

**Comment by Praxie** [comment]
v0.2.35

**Comment by Praxie** [comment]
This fix is not a part of a current release. It'll be in v0.2.35

**Comment by sives** [comment]
Working fine now.
