### ISSUE TITLE
Users online display

### ISSUE THREAD

**Issue by sives** [sives/Plio#179]
At the moment, users with their status set to "Away" don't get shown in the "users online" section on the Home screen.

The "users online" section on the Home screen should show "Away" users (with amber coloured icon), but not "Offline" users.  Otherwise there is not much point in having the different statuses.   An "Away" user is likely to be coming back, whereas an "Offline" user isn't.

**Comment by Praxie** [comment]
@sives I remember that we agreed to not show "Away" users in the "users online section".

**Comment by Praxie** [comment]
But it makes sense to show "Away" users in this section.

**Comment by sives** [comment]
Yes, sorry for change, but it does make sense
