### ISSUE TITLE
Signup process - how invitations appear to the recipient

### ISSUE THREAD

**Issue by sives** [sives/Plio#19]
When you receive the original invitation it has the Org name in a grey box (inactive).  This is confusing to the user (the recipient of the invitation).  It is easy for him to misunderstand the meaning of this field to think it is supposed to be the organisation for whom he works, and then he thinks there is an error in the invitation, and he tries to correct the error to change it to his organization name but he can't.  

Suggested solution: change the title in the Invitation header from "Accept invitation" to "Invitation to XYZ organization".   Remove the the Organization field titled "Organization name" in the Invitation card that is presented to the recipient.  Change the label on the bottom button from "Submit" to "Accept invitation".

**Comment by sives** [comment]
![screen shot 2016-05-18 at 16 48 38](https://cloud.githubusercontent.com/assets/2330529/15365528/737a2f34-1d18-11e6-81b9-634c74ce7151.png)

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/142

**Comment by sives** [comment]
Much better.  However, there needs to be a clear instruction to the user about what they need to do in the Invitation completion screen.  Suggest the following wording, on 2 separate lines at the top of the card, with no apostrophes.

Your Invitation to join the Clifton Asset Management compliance management system on Plio. 
Please enter your name and then a password to protect your account.

**Comment by sives** [comment]
You've fixed this according to my instructions, but unfortunately you've also changed the title in the card header, which I did not request.  This title should be changed back to "Accept invitation"

**Comment by Praxie** [comment]
@sives wasn't it suggested in your instructions?
> Suggested solution: change the title in the Invitation header from "Accept invitation" to "Invitation to XYZ organization".

**Comment by sives** [comment]
My apologies for the change request.  When I see it in the real system it doesn't look as good as it did in my imagination.  Can we shorten the wording in the invitation header bar to simply "Invitation"?

**Comment by Praxie** [comment]
@sives done.

**Comment by sives** [comment]
Looks good.
