### ISSUE TITLE
Non-conformity guidelines in Organization settings

### ISSUE THREAD

**Issue by sives** [sives/Plio#190]
Current field labels:
Guideline for initial risk categorization = (minor, major, critical) (x3)

Required field labels:
Guideline for classifying a minor non-conformity

Guideline for classifying a major non-conformity

Guideline for classifying a critical non-conformity

Text in box should read as:

Please go to Organization settings to define what a critical non-conformity means in your organization.  (and not Org setting, since they haven't been trained in the abbreviation yet)

**Comment by Praxie** [comment]
**v0.2.38** feature

**Comment by Praxie** [comment]
@sives what about risk guidelines?

**Comment by Praxie** [comment]
@sives
**Guideline for classifying a critical risk**
Please go to Org Settings to define what a minor risk means in your organization.

**Comment by sives** [comment]
Yes it would be good to have a field label at the top of this subcard that states:

Field label
Guideline for initial classification of a risk

Text in text box:
Please go to Organization settings to define what a minor/major/critical risk means in your organization.

**Comment by Praxie** [comment]
@sives I changed the fileld label a little:
Guideline for initial categorization of a risk

These guidelines are displaying in the top "Initial categorization" section of a Risk card.
