### ISSUE TITLE
Signup process - verification delays

### ISSUE THREAD

**Issue by sives** [sives/Plio#20]
The Verification email is not being sent until a minute or so after the user has accepted the initial invitation, which breaks the flow of the invitation process.   Yet the initial invitation email is being sent out almost instantly, why the difference in timing?  Must be something in our code that is causing it.

**Comment by sives** [comment]
We need to find a mail service that gives us a normal response time of 2-3 sec

**Comment by Praxie** [comment]
Mailgun support changed our ip address and email delivery is much faster now.

**Comment by Praxie** [comment]
I was chatting with mailjet.com support, they need to verify my account first. But I prefer mailgun.

**Comment by sives** [comment]
Working nice and fast now.
