### ISSUE TITLE
Signup process - don't verify internal invitations

### ISSUE THREAD

**Issue by sives** [sives/Plio#21]
We need to verify the email address of the first user (the Org owner) who signs up from the Register screen on the web site, and any other user that signs up from the Register screen, but we don't need to verify the email address of Users responding to emailed invitation requests (I call these "internal invitations"), because we are sending the invitation to the proper email address in the first place.  So let's delete this step, for these users.

**Comment by Praxie** [comment]
Copy that.

**Comment by Praxie** [comment]
https://trello.com/c/OHnDFt0c/152-i21-signup-process-don-t-verify-internal-invitations

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/119

**Comment by sives** [comment]
Fixed.
