### ISSUE TITLE
Signup process - problems deleting users

### ISSUE THREAD

**Issue by sives** [sives/Plio#23]
When I delete a user from the User Directory screen (I deleted steve@hoverkey.com) then a few hours later try and re-invite steve@hoverkey.com, it tells me "Failed to invite 1 user(s): User with email steve@hoverkey.com is already invited to organization".  

(I think this might have been because the max email verification time had been exceeded.  Or it might have been for another reason)

**Comment by meyginix** [comment]
https://trello.com/c/yaTH3UaX/149-i23-signup-process-problems-deleting-users

**Comment by Praxie** [comment]
https://trello.com/c/yaTH3UaX/149-i23-signup-process-problems-deleting-users

**Comment by sives** [comment]
When I delete a user (e.g. steve@hoverkey.com) from the User Directory in the Clifton organization, everything proceeds fine and the user gets deleted from the LHS List view.  However if I try and register a new organization with this deleted username, the system will not let me, saying that the email address already exists.   Once a User is deleted from the system, I should be able to re-register with that username.

**Comment by Praxie** [comment]
@sives steve@hoverkey.com is not deleted permanently from the DB. You can still log in to this account or be invited to some other organization.

**Comment by sives** [comment]
I propose the following:
!. Organisation owners
They should not be able to delete themselves.
2. All other users
If they are logged in and they go to their User profile and select "Delete user" the system should check to see how many Organisations they are a member of.  

If it is just one, then the system should pop up a dialog asking "Are you sure?" Yes/No and if the User says yes, the system should delete them completely from the system and the database.   

If the User is a member of two or more Organisations the system should prompt the User as follows:
"You are also a member of ABC and XYZ organisations in Plio.  Do you wish to delete yourself from all organisations? Yes/No"   

If the user selects Yes, then the system deletes them completely from all organisations.  If the user selects No, then the system just deletes them from the first organization.

**Comment by sives** [comment]
I'm still confused about what the agreed fix is for this issue.

**Comment by sives** [comment]
If steve@hoverkey.com is still in the DB, then why can't I use that account to create a new Organization if I want to?

**Comment by sives** [comment]
This area of the system still has a critical bug.  If I delete the user steve@hoverkey.com and then re-invite that user, the invitation process initially proceeds OK.  However, instead of being sent an email which prompts me (as steve@hoverkey.com) to accept the invitation and fill in my first name and last name, I'm presented with the "Steve Ives added you...."  email.  When I click on the Go to Dashboard button, I am taken to the Home screen, but as the incorrect user i.e. steve.ives@pliohub.com and not the new user steve@hoverkey.com.

**Comment by Praxie** [comment]
Fixed

**Comment by sives** [comment]
Works well now.
