### ISSUE TITLE
Signup process - max allowed verification time too short

### ISSUE THREAD

**Issue by sives** [sives/Plio#24]
For users who do need to verify their email address, (i.e. those registering for a new account from the web site) the allowed verification time is too short.  I got a email "verification time exceeded" message without expecting it, after just a few hours.  

It should be 24 hours and there should be a statement to the user telling them how much time they have to complete the next stage of the process whenever there is a time limit that needs to be followed, like this one.

**Comment by Praxie** [comment]
We agreed upon 3-days invitation lifetime.

**Comment by sives** [comment]
The statement to the user is contained in the message box that pops up on the top right hand side of the screen when the verification email goes out.  The message is something like "Verification email sent to [user's email address] - 3 days to reply".   The email contains the following title "Plio email verification request" and the following text. "Thank you for signing up to Plio and creating a new organization account for [Organization name].  Please click on this link to verify your email address"
