### ISSUE TITLE
General card behaviour - card closing behaviour

### ISSUE THREAD

**Issue by sives** [sives/Plio#30]
Rotating Close animation - it's not been implemented consistently across all the Close dialogs on all the Cards with all types of card update (e.g Rotating Close animation not showing when you save a thumbnail image).  

The correct implementation of the Close button should be as follows - the "Close" label should change to "Saving.." when user clicks on it (and not to "Closing.."), and show a rotating symbol to the left of the label as it saves. 

Even when it has been implemented consistently, I don't think this works yet as a concept.  The system is sometimes so quick that you can't read the closing animation in the button.  Better to display a "Changes saved" confirmation message at top right of screen **as well as** the close animation whenever you exit and save (if technically easy/possible, don't show this message if you exit when nothing has changed)

**Comment by sives** [comment]
Agreed that we would just change the button label from "Close" to "Saving.." and display a rotating symbol.  We don't need to do the message display at the top right of the screen.

**Comment by sives** [comment]
When I change something in the card, the Close button animation is working properly, but the "Close" label doesn't change to "Saving.."

**Comment by sives** [comment]
The Close button now changes to "Saving" but the card doesn't close once the saving process has completed.   Yet if you change a data item in a sub card, closing doesn't show the "Saving.." label and the card does close immediately.  Still very inconsistent behaviour.

**Comment by Praxie** [comment]
@sives I couldn't reproduce this bug.

**Comment by sives** [comment]
Working nicely now.
