### ISSUE TITLE
Search function - results line

### ISSUE THREAD

**Issue by sives** [sives/Plio#34]
Should be a line of guidance text displayed underneath the search results (e.g. "3 matching results") after the search operation has completed.   

Also, if the user leaves the screen and comes back at a later time the search term should be cleared from the search box automatically (otherwise the user can forget there is a search term in the search box and wonder why their list view is suddenly only showing a subset of all the items - where is the missing data!)

**Comment by Praxie** [comment]
![screen shot 2016-05-18 at 7 43 16 pm](https://cloud.githubusercontent.com/assets/2095940/15367227/cc3b3574-1d30-11e6-8e1e-3646d33f0b9a.png)

**Comment by Praxie** [comment]
https://trello.com/c/y1Rxez3M/146-i34-search-function-results-line

**Comment by sives** [comment]
Works nicely
