### ISSUE TITLE
Home screen - logged in users

### ISSUE THREAD

**Issue by sives** [sives/Plio#37]
Only shows yourself as the current online user on the Home screen (under the icon panel area) and not all the logged in users.  When you click out of the browser window it changes to 0 users online which is not correct either.  This area should display all users who are currently logged in, even if they have clicked out of their browser window.   (similar to Skype - it doesn't suddenly show a user as gone away if they have clicked out of Skype, but Skype is still running)

Related issue: "Away" function not implemented correctly - should only show Away when user deliberately switches to it, not when you switch a window on the system.

![users online indicator not working](https://cloud.githubusercontent.com/assets/2330529/15331552/c07444f6-1c59-11e6-92a4-8b6c7287d2d1.png)

**Comment by Praxie** [comment]
It's already fixed.

**Comment by sives** [comment]
Looks good.
