### ISSUE TITLE
User screen - dealing with invitees

### ISSUE THREAD

**Issue by sives** [sives/Plio#40]
As a recently-invited user, I am being added to the list of Users in the User Directory before I actually accept the invitation or verify my email.  This is fine, but in these cases appropriate info needs to be provided in the User screen.  In the User Details card in the Superpowers section there should be a text line at the bottom of the list of Superpowers that states either "Invitation not yet accepted by user" or "Email address not yet verified by user"

**Comment by Praxie** [comment]
Let's stick with the "Email address not yet verified by user" status

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/137

**Comment by sives** [comment]
Verified as working.
