### ISSUE TITLE
User screen - Change password

### ISSUE THREAD

**Issue by sives** [sives/Plio#43]
In the Change Password sub card, the field labels are incorrect (they shouldn't be rendered in bold, also check the font to see if it is the same as other field titles).

"Password changed" guidance text should go away once you have closed the sub card but it stays there, confusing the user.

**Comment by Praxie** [comment]
Copy that.

**Comment by sives** [comment]
![screen shot 2016-05-18 at 18 02 49](https://cloud.githubusercontent.com/assets/2330529/15367863/ce99c83e-1d22-11e6-858d-c86c1c3f6a89.png)

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/133

**Comment by sives** [comment]
Much better now.  However, after changing a password, the 3 sub card field labels - Current password, Password, Password(again) - change in colour to green which should not happen.

**Comment by Praxie** [comment]
@sives I removed the positive validation (green color) at all. I think that it's excessive for our UI.

**Comment by sives** [comment]
Looks good now.
