### ISSUE TITLE
User screen - Org owner safeguard

### ISSUE THREAD

**Issue by sives** [sives/Plio#44]
Important safeguards needed:
Ensure that the Organization Owner always has all possible superpowers, and make sure there is a programmatic check that he (or anyone else) cannot edit his superpowers to take some away.  This would have very bad consequences.

It shouldn't be possible for an Org owner to remove this status without transferring it by the proper transfer process.  The final transfer of ownership of the Organization must not happen until the new owner has actually accepted the invitation to become the owner.

**Comment by Praxie** [comment]
Org owner's superpowers should not be editable for anyone.

**Comment by Praxie** [comment]
2 enhancements:
- Show an error if the owner tries to transfer the org to the user with unverified email or not accepted invitation.
- Change 'Go to my organization to'
![screen shot 2016-06-06 at 11 13 45 am](https://cloud.githubusercontent.com/assets/2095940/15816757/0de9514e-2bdd-11e6-86f8-d11c983bfc84.png)

**Comment by Praxie** [comment]
https://trello.com/c/oJXg7ElA/198-i44-user-screen-org-owner-safeguard-8
