### ISSUE TITLE
User screen - Org owner superpowers

### ISSUE THREAD

**Issue by sives** [sives/Plio#45]
Organization Owner should be able to edit any User details, including contact details in the User details card.  They should also be able to delete any user.

**Comment by Praxie** [comment]
@sives we decided that user details information should be editable only for one user. Contact details will be shared by multiple organizations.

**Comment by sives** [comment]
Yes, I remember, but I also think it doesn't make sense as a concept

**Comment by sives** [comment]
Agreed that the system works fine as it is

**Comment by sives** [comment]
The Organization Owner should be able to delete any User, not from the entire system, but from their own Organization at least.  This is necessary to protect against abusive users.
