### ISSUE TITLE
User screen - User details top section

### ISSUE THREAD

**Issue by sives** [sives/Plio#47]
2 fields missing from top section of User card
i) Desktop notifications on/off (when there is a Plio notification, you get a desktop notification on Windows or OS X via appropriate push notification services. Default is "On")
ii) Notification sound (selection of 10 sounds, or none)

**Comment by Praxie** [comment]
It's more like an enhancement, not a bug.
Was it going to be a part of the user directory? Does it make sense to include this in the user profile card if we can create a separate "Preferences" modal window?

> ii) Notification sound (selection of 10 sounds, or none)

Will you provide 10 notification sounds?

**Comment by sives** [comment]
We previously agreed to merge the User settings (which only had these two features) into the User profile card, to simplify the system - so it's not really an enhancement

**Comment by sives** [comment]
This settings should go back into a User preferences card, accessed from the right hand side dropdown menu in the Home screen

**Comment by Praxie** [comment]
![screen shot 2016-06-14 at 11 22 35 am](https://cloud.githubusercontent.com/assets/2095940/16035946/62b5d24c-3222-11e6-90e0-ae5a3db3075d.png)
