### ISSUE TITLE
User screen - User details contact info

### ISSUE THREAD

**Issue by sives** [sives/Plio#48]
Need a comma between the different address lines when the address is rendered as one continuous line in the Read mode of the card (unless user has already put commas in when entering address text in the Edit mode of the card, in which case the system shouldn't put in a second comma in Read mode!)

Country selection - shouldn't default to Afghanistan, but to the UK.   The list of countries should have some primary financial services countries (USA, Singapore, Paris, Frankfurt, Hong Kong) at the top of the list before listing every country in the world.

**Comment by Praxie** [comment]
> Need a comma between the different address lines when the address is rendered as one continuous line in the Read mode of the card (unless user has already put commas in when entering address text in the Edit mode of the card, in which case the system shouldn't put in a second comma in Read mode!)

Could you provide an example?

**Comment by sives** [comment]
For example, Plio's office address in London when written out on one line is:
Level39, One Canada Square, Canary Wharf, London, E14 5AB.

Note the commas between each element of the address and the full stop at the end.
The address entry box in Plio is relatively narrow, so some users would be expected to type in the address like this:

Level39
One Canada Square
Canary Wharf
London
E14 5AB

or some users might type it in like this:

Level39,
One Canada Square,
Canary Wharf,
London,
E14 5AB

Whichever way they type it in, we have to display it as a one line address with commas when we display it in the Read mode of the card (as shown at the top of this Comment post).

**Comment by Praxie** [comment]
We can replace new line symbols (\n) with "," while saving it into the database.

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/121

**Comment by sives** [comment]
Works well
