### ISSUE TITLE
User screen - Org owner display

### ISSUE THREAD

**Issue by sives** [sives/Plio#49]
In the Superpowers sub card, if the user is the Organization owner, then this fact should be displayed underneath his list of Superpowers (not with a checkbox, just as a text string "Organization owner for Organization XYZ").

**Comment by meyginix** [comment]
https://trello.com/c/gUrAYMba/202-i49-user-screen-org-owner-display

**Comment by Praxie** [comment]
https://trello.com/c/gUrAYMba/202-i49-user-screen-org-owner-display-0-7

**Comment by Praxie** [comment]
@sives 
(Default) https://notificationsounds.com/message-tones/graceful-285
https://notificationsounds.com/wake-up-tones/arpeggio-467
https://notificationsounds.com/message-tones/all-eyes-on-me-465
https://notificationsounds.com/notification-sounds/coins-497
https://notificationsounds.com/notification-sounds/job-done-501
https://notificationsounds.com/message-tones/gets-in-the-way-520
https://notificationsounds.com/standard-ringtones/isnt-it-524
https://notificationsounds.com/message-tones/oringz-w428-315
https://notificationsounds.com/notification-sounds/you-wouldnt-believe-510
https://notificationsounds.com/message-tones/office-1-294

**Comment by vikyngo** [comment]
http://bestringtones.net/message-alert-tones.html
[message ringtones](http://bestringtones.net/message-alert-tones.html)

**Comment by Jessiejames-0911** [comment]
best [hanoi tours](http://www.aprotravel.com/travel-styles/day-trips-from-hanoi/) in vietnam

**Comment by kangpaper** [comment]
https://github.com/magento-2/one-step-checkout
https://www.facebook.com/notes/mageplaza/magento-2-one-step-checkout/1778552102423988
https://www.linkedin.com/pulse/magento-2-one-step-checkout-extension-mageplaza-mageplaza-1
http://bestonestepcheckout.blogspot.com/2016/09/magento-2-one-step-checkout-extension.html
http://www.magechoice.com/magento-2-one-step-checkout

**Comment by johnbasssic** [comment]
[cho thuê xe ô tô đà nẵng](http://chothuexevip.vn/cho-thue-xe-o-to-da-nang.html)

**Comment by hoangtuanhd87** [comment]
http://khangdienhouse.com/du-an-can-ho-cao-cap-khang-dien/
http://canho24h.info/
http://canho24h.info/sunrise-riverside-can-ho-cao-cap-ven-song-rach-dia-nha.html
http://khangdienhouse.com/du-an-khu-thi-khang-dien-binh-chanh/
http://khangdienhouse.com/du-an-monada-khang-dien/

**Comment by annakieu** [comment]
[](https://threelinks.org/assisted-living/)
[](https://threelinks.org/senior-centers-minnesota/)
