### ISSUE TITLE
Org settings card - Standards book sections sub card

### ISSUE THREAD

**Issue by sives** [sives/Plio#51]
In this sub card, there should be no Section names entered as default values, these should be blank when you create a new Organization.  Section names will vary a lot between each Organization, it makes no sense to have default values.

**Comment by Praxie** [comment]
@sives There are no section names default values for new organizations, only categories.
Did you create a new account? Maybe it was fixture data from the Clifton organization.
![screen shot 2016-05-18 at 12 58 08 pm](https://cloud.githubusercontent.com/assets/2095940/15354853/3d5cb7e8-1cf8-11e6-8644-111929c48174.png)

**Comment by Praxie** [comment]
I found the error. We're subscribing to the data from all current user organizations.
We need to subscribe only to Organisations.find({ … }, { fields: { name: 1 } }) in the header to display org names and currentUserOrganizationBySerialNumber/currentUserOrganizationById if possible.
In the section select input we need to filter standards by orgnizationId as well in case we'll be chaching subscriptions in the future.

**Comment by RevelsGit** [comment]
https://trello.com/c/gJUCQkrG/142-bug-org-settings-card-standards-book-sections-sub-card

**Comment by sives** [comment]
OK great

**Comment by sives** [comment]
I could not test this, since I couldn't find a way to register a new organization with my existing set of email addresses

**Comment by Praxie** [comment]
@sives https://github.com/sives/Plio/issues/77 is fixed and deployed

**Comment by sives** [comment]
Now works according to the spec.
