### ISSUE TITLE
Org settings - incorrect error message

### ISSUE THREAD

**Issue by sives** [sives/Plio#53]
I Get a message telling me that I'm not authorised to change Org Settings when I try to change some, even though my User Profile tells me I am authorised.

**Comment by Praxie** [comment]
Copy that.

**Comment by Praxie** [comment]
https://trello.com/c/CSycWiwt/141-user-is-not-authorized-for-editing-organization-settings-even-if-he-is

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/107

**Comment by sives** [comment]
Working now.
