### ISSUE TITLE
Standards book screen - adding new documents

### ISSUE THREAD

**Issue by sives** [sives/Plio#54]
When adding a new document, the New Section option is not operating in a sensible way - its giving you a new section with a name that you can't specify when you create it, which makes no sense.  

When you add a new Section and go to Org Settings to change its name, and go back to Standards book, the changed name doesn't show up in the Sections list.

Let's make Sections treatable and editable only in Org Settings, and with a separate user Superpower that allows you to create and edit Sections (with only the Org Owner getting this Superpower by default).   As I have said previously a few times, and as stated in the Screen spec v1.1, there are no default values for Sections, they have to entered by the user.

**Comment by Praxie** [comment]
> When adding a new document, the New Section option is not operating in a sensible way - its giving you a new section with a name that you can't specify when you create it, which makes no sense.

It works fine for me. You can specify the section name.
![may-18-2016 13-17-39](https://cloud.githubusercontent.com/assets/2095940/15355388/fd0fc3a8-1cfa-11e6-83ef-e33a6f87220b.gif)

**Comment by sives** [comment]
I tested it again after creating a new Organization, and it seems to work fine.  So we can mark this as a non-bug
