### ISSUE TITLE
Standards book screen - deleting departments

### ISSUE THREAD

**Issue by sives** [sives/Plio#55]
Tried to delete a Department in Org Settings (as steve.ives@pliohub.com, who as the Org owner has the superpower to change Org Settings) and found that I couldn't.  I got an error message "User is not authorized for editing organization settings".

**Comment by Praxie** [comment]
@sives The section name can't be deleted as well. That's the reason of superpowers validation. It's been overlooked.

**Comment by Praxie** [comment]
#53

**Comment by Praxie** [comment]
https://trello.com/c/CSycWiwt/141-user-is-not-authorized-for-editing-organization-settings-even-if-he-is

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/107

**Comment by sives** [comment]
Working now
