### ISSUE TITLE
Standards book screen - file attachments

### ISSUE THREAD

**Issue by sives** [sives/Plio#56]
File attachments are not working properly - for some files I tested, I got a notification of "URL is not valid!" error at the top of the card and the file does not attach to the card.  For other files, it seems to attach OK. I couldn't work out any reason why some files attached and some didn't.  It might be related to filename, file size or file type, but I couldn't find a reason.   

Even when it attaches correctly the file cannot be downloaded and read from the read mode of the card.  So attachments seem to be totally broken (on Safari 9.1 at least)

**Comment by Praxie** [comment]
@sives You got the "URL is not valid!" error because your URL didn't start with http:// and thus the link in the read mode would be broken.

**Comment by Praxie** [comment]
I found out that there is a bug with adding new files from the computer.
It worked locally so the problem is with Amazon configurations.
For links the user should include “http://“ or “https://” at the beginning of the url to make it valid.
We can check if there is “http://“ or “https://” and add this part to the url string if not.

**Comment by meyginix** [comment]
https://trello.com/c/FhMgQ4Rl/138-major-bug-standards-book-screen-file-attachments

**Comment by sives** [comment]
Seems like a good solution.  Someone needs to test adding a file that is on Microsoft OneDrive (on the Microsoft cloud), since that is the most likely use case and is in the spec.  I'm a Mac user, not a Microsoft user, so I'm not an ideal tester for this.

**Comment by sives** [comment]
I tried to add the following URL to a standards document
https://docs.google.com/document/d/1YxmUTuK9Xl1Zi137kHdCIlJqIwoB45uSW4K45ZBDVGs/edit

It does not work (it doesn't save in the URL field when you try to save it)

Yet if I save it in another system (e.g. Microsoft Word) the URL saves and links properly to the document.

**Comment by sives** [comment]
You can now add new files OK from non-local sources.  However, when you click on the file link in the card, it downloads the file and opens a new browser window called "untitled".  It should just download the file and not open a new browser window (why do this? - it just takes the user away from the screen that they are working on, without any reason.  When you click in a .docx file link in a Google search results page it doesn't open a new browser window)

**Comment by Praxie** [comment]
@sives Safari doesn't support this.
Suggested workaround:
We can show a hint for each download link in Safari by using Modernizr package.
![download-attr-safari](https://cloud.githubusercontent.com/assets/2095940/15616606/9f847daa-244d-11e6-99fc-90d59db84deb.jpg)

**Comment by Praxie** [comment]
In other browsers it works. The future version of Safari might support this feature.

**Comment by Praxie** [comment]
There's no other simple way to do this.

**Comment by sives** [comment]
Mike - Mammoth is a server side framework, not client side. Its compatibility issues relate to NodeJS, not to browsers

**Comment by Praxie** [comment]
@sives Mammoth has nothing to do with this. We're not implementing docx-rendering yet.
I was talking about file downloading triggered by clicking on file's label.

**Comment by Praxie** [comment]
@meyginix found a way to solve it with the help of Amazon

**Comment by sives** [comment]
OK great

**Comment by sives** [comment]
Works really nicely now with my Mac + Safari setup.
