### ISSUE TITLE
Standards book screen - file attachments labelling

### ISSUE THREAD

**Issue by sives** [sives/Plio#57]
Rename "Source document/video 1" to "Source file" - less confusing.
Don't show the Source file 2 option until user has added something first i.e. Source file 1. (I have mentioned this requirement previously)

**Comment by Praxie** [comment]
Copy that. 

I found another small bug. The number of the second attachment should be 2, not 1.
![screen shot 2016-05-18 at 1 08 06 pm](https://cloud.githubusercontent.com/assets/2095940/15355107/9ca4dc5c-1cf9-11e6-8dbb-f1a7fce469ea.png)

**Comment by sives** [comment]
Yes, this needs fixing too

**Comment by meyginix** [comment]
https://trello.com/c/S16zVnUz/150-i57-standards-book-screen-file-attachments-labelling

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/123

**Comment by Praxie** [comment]
I removed '1' from 'Source file 1' btw.
![screen shot 2016-05-20 at 8 40 38 pm](https://cloud.githubusercontent.com/assets/2095940/15436578/626c82fa-1ecb-11e6-9636-848a660cf21a.png)

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/123

**Comment by sives** [comment]
Looks good
