### ISSUE TITLE
Standards book screen - Notify subcard

### ISSUE THREAD

**Issue by sives** [sives/Plio#58]
The Notify function isn't working.   If you create a document in the Standards Book, you should be on the Notify list automatically.  If you add people to this list, they should be notified by Email that they are on the notification list for this document.  If there are any changes to the Standard card (e.g. change in Title, Description , Issue number or source URL), they should be notified of these changes.

Change Notify sub card title to "Notify changes" to make intention clearer.

**Comment by Praxie** [comment]
Copy that.
I imagined the notification via email feature to be a part of the Milestone 3.

**Comment by meyginix** [comment]
https://trello.com/c/b6f6yNmi/139-major-bug-standards-book-screen-notify-subcard

**Comment by sives** [comment]
Fine with me to allocate to Milestone 3a (need to get that milestone into Github)

**Comment by Praxie** [comment]
> If you create a document in the Standards Book, you should be on the Notify list automatically.
If you add people to this list, they should be notified by Email that they are on the notification list for this document.
Change Notify sub card title to "Notify changes" to make intention clearer.

This should be the Milestone 2b

> If there are any changes to the Standard card (e.g. change in Title, Description , Issue number or source URL), they should be notified of these changes.

This one I propose to move to the Milestone 3a.

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/138

**Comment by sives** [comment]
Milestone 2b fix has been implemented and is working.  I will leave this issue open because of the Milestone 3a fix.
