### ISSUE TITLE
Standards book screen - owner

### ISSUE THREAD

**Issue by sives** [sives/Plio#59]
If you are the Owner of the Standard, and you go and edit it and click into the Owner field that by default contains your own name, your name disappears and you can't reselect it from the list underneath or get it back by moving out of the field.  You should be able to.

**Comment by Praxie** [comment]
Copy that. 
It's a bug.

**Comment by RevelsGit** [comment]
https://trello.com/c/F0REzr7W/137-bug-standards-book-screen-owner

**Comment by Praxie** [comment]
The solution is to select the text in the selectable input automatically after a click.
Then the user will remove the text and start typing or start typing and it'll remove the text automatically.

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/131

**Comment by sives** [comment]
Working fine now.
