### ISSUE TITLE
standards book screen - improvement plan sub card

### ISSUE THREAD

**Issue by sives** [sives/Plio#61]
Rename field title in card Edit mode from "Means statement" to "Means statement - file attachment" and use a similar but shorter field title i.e. "Means statement"  in the Read mode of the card (at the moment it says Means statement in Edit mode and a different title - Files - in Read mode)

**Comment by Praxie** [comment]
@sives Copy that

**Comment by RevelsGit** [comment]
https://trello.com/c/H0J4i50t/136-bug-standards-book-screen-improvement-plan-sub-card

**Comment by sives** [comment]
Means statement file attachment feature not working yet

**Comment by sives** [comment]
It now works.
