### ISSUE TITLE
Standards book screen - lessons learned sub card

### ISSUE THREAD

**Issue by sives** [sives/Plio#62]
These are not saving properly - I'm wondering if this sub card been completely implemented?   The Linked to field should display the name of the Standards Book document to which it is linked, when a new Lesson Learned is added. The Created date should default to today's date, and Created By should default to the user. 

The design of the Large expandable text field in the Lessons Learned sub card can be improved. There should be the normal card header and card footer bar displayed when in expanded mode.  At the moment these are not present.  (General rule as stated in the Screen spec v1.1 - every card should always have a card header and a card footer).  Also the default font size for the text should be one point bigger.

**Comment by Praxie** [comment]
What should be in the left-side label box if the linked entity is a standard?
![screen shot 2016-05-18 at 11 15 34 am](https://cloud.githubusercontent.com/assets/2095940/15351841/fbfe31f4-1ce9-11e6-9f54-0672a20c9bfc.png)

**Comment by Praxie** [comment]
Does it look better? (Round green 'repeat' botton is a chrome extension, it's not part of the ui)
![screen shot 2016-05-18 at 10 44 15 am](https://cloud.githubusercontent.com/assets/2095940/15351883/318bc958-1cea-11e6-98ad-217a233d16fd.png)
![screen shot 2016-05-18 at 10 44 26 am](https://cloud.githubusercontent.com/assets/2095940/15351885/3390c78a-1cea-11e6-8c38-d2ff7b25fa32.png)

**Comment by RevelsGit** [comment]
https://trello.com/c/EFnMOp5H/135-major-bug-standards-book-screen-lessons-learned-sub-card

**Comment by sives** [comment]
Yes, much better. Font size could be even one or two points bigger (average age of a compliance manager is 45 - eyes find it harder to read v small text at this age!)

**Comment by Praxie** [comment]
We can remove the left-hand box for standards. 
It's not editable so we'll have another field for non conformities.

**Comment by Praxie** [comment]
https://trello.com/c/EFnMOp5H/135-i62-major-bug-standards-book-screen-lessons-learned-sub-card

**Comment by sives** [comment]
One small issue - when you are in an existing Standards card and you then create a new Lessons Learned sub card and start adding a title etc, the "Linked to" field (the grey box) should already be pre-filled with the name of that Standard card.  This behaviour applied to any "Linked to" field.

**Comment by sives** [comment]
Linking behaviour now works as it should.
