### ISSUE TITLE
Standards book screen - lessons learned List view option

### ISSUE THREAD

**Issue by sives** [sives/Plio#63]
Need a Lesson Learned List view option in the header bar List View selector.
(List view detail:  Title on line 1 in larger font, Linked to (standards document title) on line 2 in smaller font)

When you've added a Lesson Learned to a Standards document, and you go to Read mode of the Standards card and click on the Lessons Learned button (which has a unique ID e.g. LL123) , it should take you to this List View, automatically opening it to select and display the Lessons Learned card LL123 on the right hand side  .

**Comment by sives** [comment]
We will also need a "Standards - deleted" List view

**Comment by Praxie** [comment]
> We will also need a "Standards - deleted" List view
Done.

Lesson Learned List view is on hold as I understand.
