### ISSUE TITLE
General sub card behaviour - text presence icon

### ISSUE THREAD

**Issue by sives** [sives/Plio#64]
The text presence indicator displayed on the sub card headers in Edit mode in the Improvement Plan and Lessons Learned sub cards (on right hand side) should only be displayed if text has been entered in the sub card.  Currently it is displaying all the time.

**Comment by Praxie** [comment]
@sives Could you explain it a little bit more? There are multiple fields in the Improvement Plan subcard. Should we display the text presence icon if at least one of them was filled? What about date/files fields?

**Comment by sives** [comment]
The text presence icon should be displayed if any text has been entered into the "Statement of desired outcome" text field.   Don't worry about the contents of any other fields.

**Comment by sives** [comment]
Working well now.
