### ISSUE TITLE
Standards book screen - amended list of types

### ISSUE THREAD

**Issue by sives** [sives/Plio#65]
There are now 8 different Standards types (editable in Org settings), and the names and abbreviations have changed slightly.

Policy (POL)
Checklist (CHK)
Standard Operating Procedure (SOP)
Work instruction (WRK)
Product specification (SPC)
Test method (TST)
Regulation (REG)
Other (DOC)

**Comment by Praxie** [comment]
https://trello.com/c/57TtjhZh/147-i34-standards-book-screen-amended-list-of-types

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/114

**Comment by sives** [comment]
These Standard types need to be listed in the order that I listed them above, and not in the order that they are currently implemented in

**Comment by Praxie** [comment]
![screen shot 2016-05-30 at 11 57 58 am](https://cloud.githubusercontent.com/assets/2095940/15644809/cf738b34-265d-11e6-8536-df3d1e92b104.png)

**Comment by Praxie** [comment]
We'll need to reset the database to owerwrite fixtures (dummy data).

**Comment by sives** [comment]
Layout shown above looks good

**Comment by sives** [comment]
All now working according to the spec.
