### ISSUE TITLE
Home screen - icon title

### ISSUE THREAD

**Issue by sives** [sives/Plio#66]
The Standards icon that leads to the Standards screen should be called "Compliance standards", to make its purpose clearer to new users.

This only needs to be changed in three places - the Home screen and in the Standard screen header, and in the Standard card header (Read and Edit modes) - the other instances of the term can be left as the single word Standards, for brevity.

**Comment by RevelsGit** [comment]
https://trello.com/c/ZgpJV3ko/153-i66-home-screen-icon-title

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/120

**Comment by sives** [comment]
Looks good.
