### ISSUE TITLE
The deleted user still has an access to the organization that he was deleted from

### ISSUE THREAD

**Issue by Praxie** [sives/Plio#77]

**Comment by sives** [comment]
Working well now.

**Comment by sives** [comment]
The original issue is fixed i.e. I delete a user, and that user is now properly deleted from the organization and I can't login as that user.  However, there is a new problem.   If I delete a user and then click on the Login button on the initial login screen, I get this message displayed (even before I've entered my login details)

![screen shot 2016-06-01 at 09 57 18](https://cloud.githubusercontent.com/assets/2330529/15703842/7f9d0e4a-27df-11e6-911e-e1cdbf3161f6.png)

**Comment by Praxie** [comment]
@sives I believe that 'delete user permanently' wasn't a part of Milestone 2b and it's more like an enhancement to Milestone 2c/3.

**Comment by sives** [comment]
On re-testing, this function seems to be working fine now.
