### ISSUE TITLE
General card behaviour - selection options indicator

### ISSUE THREAD

**Issue by sives** [sives/Plio#80]
If a data entry field in a card has existing selection options (e.g. a list of Users) then there should be a down-pointing chevron indicator at the RHS of the field box.  This got missed from the latest version of the UI prototype, but was in earlier versions of the prototypes (see below).   Lets make sure this feature is in all new screens.

![screen shot 2016-05-27 at 14 32 54](https://cloud.githubusercontent.com/assets/2330529/15609498/4921d14a-2418-11e6-8ddd-fd1423bdd0c5.png)

**Comment by Praxie** [comment]
@sives what is the difference between Contacts and Users?

**Comment by sives** [comment]
@praxie that is from an old prototype which allowed you to store contact details for people who were not actual Users of Plio, but which you might need to keep in the database.  We don't need to worry about Contacts in the system we are building right now.
