### ISSUE TITLE
Mobile - Standards screen bug

### ISSUE THREAD

**Issue by sives** [sives/Plio#82]
When entering the Compliance Standards screen on mobile device the keyboard pops up - it wants you to enter a search term, even if the user hasn't tapped onto the search box.    It should just go into the Compliance Standards screen and display a list of Standards without popping up the search box.

**Comment by Praxie** [comment]
@sives what device are you using? I can't reproduce this issue on iPhone 5.

**Comment by sives** [comment]
Works fine now
