### ISSUE TITLE
Mobile - login screen not displaying conveniently

### ISSUE THREAD

**Issue by sives** [sives/Plio#84]
On mobile on the Login screen, the top grey section with the Plio logo takes up too much space, so that you have to scroll down before you can login.   The same problem happens with the Sign Up screen.

The email and password fields should display above the mobile virtual keyboard, without having to scroll the screen.

**Comment by sives** [comment]
Still not fixed, see screenshot.  Both email and password fields should be visible, together with the login button, in the screen region above the virtual keyboard.   (The challenge is to create a login screen that meets this requirement on mobile but also looks OK on the desktop)

![screenshot_2016-06-01-10-09-18](https://cloud.githubusercontent.com/assets/2330529/15704174/56014f7c-27e1-11e6-914e-e222bc1207c7.png)

**Comment by Praxie** [comment]
I made it as convenient as possible.
Better effect could be accomplished in native application.

**Comment by sives** [comment]
Just tested it - works well
