### ISSUE TITLE
User screen - Superpowers sub card label incorrect

### ISSUE THREAD

**Issue by sives** [sives/Plio#85]
The label on the sub card should just be "Superpowers".   

The longer label e.g. "stephen.ives@pliohub.com's superpowers for Clifton Asset Management plc" should only be shown in the sub card when the sub card is opened. It should be displayed above the list of checkboxes (in normal text, not in bold) and not in the sub card header.

**Comment by Praxie** [comment]
![screen shot 2016-05-30 at 11 09 19 am](https://cloud.githubusercontent.com/assets/2095940/15643616/0d19d8dc-2657-11e6-87cf-86120e45a775.png)

**Comment by Praxie** [comment]
@sives I don't like how it looks. I think that it's better to remove the "stephen.ives@pliohub.com's superpowers for Clifton Asset Management plc" label at all.

**Comment by Praxie** [comment]
![screen shot 2016-05-30 at 11 33 45 am](https://cloud.githubusercontent.com/assets/2095940/15644234/6faa5b22-265a-11e6-8eec-583bdff81dcc.png)

**Comment by sives** [comment]
Looks fine
