### ISSUE TITLE
There is no way to remove the mobile number from the user profile

### ISSUE THREAD

**Issue by Praxie** [sives/Plio#87]
@sives Shall we do something like this?
![screen shot 2016-05-30 at 6 19 10 pm](https://cloud.githubusercontent.com/assets/2095940/15653045/28381fca-2693-11e6-8370-534fe1eac3bf.png)

**Comment by Praxie** [comment]
Also, we can resize the "Add" button properly. 
min-width: 60% will work for most cases.
![screen shot 2016-05-30 at 6 25 30 pm](https://cloud.githubusercontent.com/assets/2095940/15653187/01577710-2694-11e6-813d-76181a845c95.png)

**Comment by sives** [comment]
Agreed - this looks good
