### ISSUE TITLE
Icon footer looks inconsistent after the "Standards" title was changed to "Complience standards"

### ISSUE THREAD

**Issue by Praxie** [sives/Plio#88]
![screen shot 2016-05-31 at 10 08 30 am](https://cloud.githubusercontent.com/assets/2095940/15666152/cf3ec628-2717-11e6-8efa-5a835914c6b1.png)

**Comment by Praxie** [comment]
@sives is it better now?
![screen shot 2016-05-31 at 10 13 09 am](https://cloud.githubusercontent.com/assets/2095940/15666248/78d8befa-2718-11e6-965c-1afb83591bcf.png)

**Comment by sives** [comment]
Yes that's better
