### ISSUE TITLE
Signup process - wording of invitation email

### ISSUE THREAD

**Issue by sives** [sives/Plio#90]
Needs amending as follows:

Current:
"Steve Ives invited you to the "Clifton Asset Management plc" organization!"

Desired:
"Steve Ives invited you to join the Clifton Asset Management plc compliance management system"
(note - do not use quote marks around the organization name)

Current:
"Hi there Steve.  We'll be using Plio to store documents, complete worksheets and track issues during this project.  See you soon"

Desired:
"Hi there Steve. We'll be using Plio to share compliance standards documents, to record non-conformities and risks and to track actions.  See you soon."

**Comment by Praxie** [comment]
https://github.com/JSSolutions/Plio/pull/190
