### ISSUE TITLE
Docx conversion - file uploading issues

### ISSUE THREAD

**Issue by sives** [sives/Plio#98]
When you upload a file, there should be some kind of indication of progressive page load, e.g. transparent grey bar moving left to right across the file name box.

The rotating icon animation that you use while the file is loading should be the same animation as you use with the Close button when a card is saving, doesn't make sense to use a different icon animation.

When the file has fully uploaded, the text icon is then displayed at the RHS of the sub card.  Sometimes this icon spins as well, sometimes it doesn't.   Should be more consistent in its behaviour.

**Comment by Praxie** [comment]
Resolved and is ready for testing

**Comment by Praxie** [comment]
Add a minimum time of the anization (for small files)
