### ISSUE TITLE
Docx conversion - problem deleting the docx attachment

### ISSUE THREAD

**Issue by sives** [sives/Plio#99]
When deleting a docx attachment, sometimes I was able to do this OK.

Sometimes the system went off into Saving... mode for a long time before it deleted, and then deleted the document attachment from the card, but still left the HTML rendered text visible in the main text display window.

Sometimes the system went off into Saving.. mode and would not complete the operation.

Not sure if this issue is related to some performance problem we are having with the system, or it is caused by a bug in the code.

**Comment by Praxie** [comment]
I couldn't recreate this issue.

**Comment by Praxie** [comment]
Resolved
